### ISSUE TITLE
Input Example Not Running

### ISSUE THREAD

**Issue by CoryKornowicz** [limresgrp/FMAP_v1#3]
When trying to run the input example through 
```bash
plumed driver --plumed plumed.dat --mf_pdb start.pdb
```
it returns an error about the listed indexes not being found, and upon looking at the start.pdb file, they are in fact not there. Could you upload a full input example for testing?

**Comment by h2nch2co2h** [comment]
Hi, 

I added the file containing all atoms.

This should allow you to run the driver.
